### ISSUE TITLE
there are two errors

### ISSUE THREAD

**Issue by royburns** [kituyiharry/peek#1]
error: Target of URI doesn't exist: 'package:peek/main.dart'. (uri_does_not_exist at [yame] test\widget_test.dart:11)

error: The function 'ValuePeekApp' isn't defined. (undefined_function at [yame] test\widget_test.dart:16)

Due to the version of Flutter?

Below is my configuration
------------------------------------
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by royburns** [comment]
maybe i have fixed this issue.

.\peek\test\widget_test.dart
//import 'package:peek/main.dart';
import 'package:yame/main.dart';

**Comment by kituyiharry** [comment]
Yeah, there were changes to the package name. Will update from here.
