### ISSUE TITLE
File google-services.json is missing. 

### ISSUE THREAD

**Issue by royburns** [kituyiharry/peek#2]
Launching lib\main.dart on MI 5s in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  E:\workspace\AndroidStudioProjects\peek\android\app\src\nullnull\debug\google-services.json
  E:\workspace\AndroidStudioProjects\peek\android\app\src\debug\nullnull\google-services.json
  E:\workspace\AndroidStudioProjects\peek\android\app\src\nullnull\google-services.json
  E:\workspace\AndroidStudioProjects\peek\android\app\src\debug\google-services.json
  E:\workspace\AndroidStudioProjects\peek\android\app\src\nullnullDebug\google-services.json
  E:\workspace\AndroidStudioProjects\peek\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by royburns** [comment]
do i need to go to Firebase to download the file?

**Comment by royburns** [comment]
i have already run the app on my android, thanks very much
you can close the two issue,pls

**Comment by kituyiharry** [comment]
Woops! Hello there, Sorry for the delay seems you were missing the analytics file. Good thing you solved it.
Closing the issue
