### ISSUE TITLE
Can you share clear instructions on how and where to add the API keys for IEX?

### ISSUE THREAD

**Issue by dgurudot** [kituyiharry/peek#3]
As you mentioned, IEX stopped API without keys, so kindly let us know where to add that key in code.

**Comment by kituyiharry** [comment]
Currently i haven't added support to using API keys in the code since I don't personally have an API key to test. I'm not actively developing the project but I'll try working on it soon.

Pull requests are welcome :)

**Comment by dgurudot** [comment]
You can register for free account and that provides api key.

I tried to do it but couldn’t figure it out so far which is why checking.

**Comment by kituyiharry** [comment]
@dgurudot I just did.. I'm working on cleaning up the API. I have added a way to use a token with the sandbox endpoint. You can check [this file](https://github.com/kituyiharry/peek/blob/master/lib/network/iex_api_proxy.dart) Further improvements will come later as i mostly work on this during my free time.

Edit: You can use a token from IEX to test the sandbox, Just replace  _[YOUR TOKEN HERE]_ with the value for the token

**Comment by dgurudot** [comment]
Nice ... there was a minor compile error but I was able to fix it by looking at history. I added sandbox token (IEX doesn't accept production) and everything started working now.

**Comment by kituyiharry** [comment]
Closing this issue for now...Until i figure out the new API
